# Generated by Django 6.0.3 on 2026-04-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='services',
            name='arrangements',
        ),
        migrations.RemoveField(
            model_name='services',
            name='service',
        ),
        migrations.AddField(
            model_name='services',
            name='cover_picture',
            field=models.ImageField(default='default_service_cover.jpg', upload_to='service_covers/'),
        ),
        migrations.AddField(
            model_name='services',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='services',
            name='title',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='services',
            name='tags',
            field=models.ManyToManyField(blank=True, to='app.tags'),
        ),
    ]
