# Generated by Django 6.0.3 on 2026-05-06 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='services_done',
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_consumer', to='app.profile')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_provider', to='app.profile')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_service', to='app.services')),
            ],
        ),
        migrations.AddField(
            model_name='dashboard',
            name='bookings_done',
            field=models.ManyToManyField(blank=True, related_name='dashboard_bookings_done', to='app.bookings'),
        ),
    ]
