# Generated by Django 6.0.3 on 2026-05-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_dashboard_services_done_bookings_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_Extras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.CharField(max_length=16)),
                ('rate', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_extras', to='app.services')),
            ],
        ),
        migrations.AddField(
            model_name='bookings',
            name='extras',
            field=models.ManyToManyField(blank=True, related_name='booking_extras', to='app.event_extras'),
        ),
    ]
