# Generated by Django 6.0.3 on 2026-05-07 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_event_extras_bookings_extras'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookings',
            name='guests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='varification_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='account_type',
            field=models.CharField(default='client', max_length=16),
        ),
    ]
