# Generated by Django 6.0.3 on 2026-05-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='years_active',
            field=models.IntegerField(default=0),
        ),
    ]
