# Generated by Django 6.0.3 on 2026-05-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_profile_years_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='upcoming_bookings',
            field=models.ManyToManyField(blank=True, related_name='dashboard_upcoming_bookings', to='app.bookings'),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='performance',
            field=models.FloatField(default=0.0),
        ),
    ]
