# Generated by Django 6.0.3 on 2026-05-08 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_dashboard_upcoming_bookings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateField(default=None, null=True),
        ),
    ]
