# Generated by Django 6.0.3 on 2026-05-08 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_bookings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='location',
            field=models.CharField(default='Faisalabad', max_length=32),
        ),
    ]
