# Generated by Django 6.0.3 on 2026-05-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_bookings_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='rate',
            field=models.IntegerField(default=50),
        ),
    ]
