# Generated by Django 6.0.3 on 2026-06-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_services_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='varification_status',
        ),
    ]
