# Generated by Django 6.0.3 on 2026-06-05 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_profile_varification_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='years_active',
        ),
        migrations.AddField(
            model_name='profile',
            name='tagline',
            field=models.CharField(default='', max_length=32),
        ),
    ]
