# Generated by Django 6.0.3 on 2026-06-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_remove_profile_years_active_profile_tagline'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='contact',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
    ]
