# Generated by Django 6.0.3 on 2026-06-06 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_profile_contact_delete_dashboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='category',
            field=models.CharField(default='Other', max_length=32),
        ),
    ]
